### ISSUE TITLE
Wrong mainProgram for the OpenFOAM adapter

### ISSUE THREAD

**Issue by MakisH** [precice/nix-packages#5]
Looking at the recipe for the OpenFOAM adapter, I see:

https://github.com/precice/nix-packages/blob/982c65399c6b01d3bdd372d5ebeecd2901821047/precice-packages/openfoam-adapter/default.nix#L47

`elasticity` sounds like the example solver included in the deal.II adapter. The OpenFOAM adapter does not include any main program, only a shared library.

Do we really need to specify this `mainProgram` for every package?

**Comment by cheriimoya** [comment]
No, we don't need it for every package. This variable is only for the `nix run` tooling, so you can directly run executables. Must have been a copy-paste error, but this has already been fixed in f124feb
